### ISSUE TITLE
LilyPad Petals need a new name per the engineering standard...

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/LilyPad_Simple_Power#2]
The petals do not adhere to the naming standard (should probably fall under the "Connectors and Headers" category with the "JP" prefix)

**Comment by ToniCorinne** [comment]
I'm not sure what else you mean besides the JP prefix, but I updated that.

**Comment by ericorosel** [comment]
that was it, sorry for the confusion.

**Comment by ToniCorinne** [comment]
Cool, just wanted to make sure! Thanks!
