### ISSUE TITLE
Exposed traces

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/LilyPad_Simple_Power#4]
The PWR and GND traces from the USB are exposed. This is tricky given the tight lilypad parameters and design. Might be worth getting clear solder mask over those traces to preserve the look, or might not be worth fixing at all.

I'll leave this up to engineering.

**Comment by ToniCorinne** [comment]
There are enough other places on this board that users will short out long before that part, so I'm going to leave this as-is.
